[book]
title = "SQE — Sovereign Query Engine"
authors = ["The SQE Project"]
language = "en"
src = "src"

[build]
build-dir = "./book"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/getsqe/docs"
additional-css = []
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html.fold]
enable = true
level = 1
